#!/bin/bash
conflict

while [ -f conflict_content.con ]
do
vim conflict_content.con
conflict
done

if [ -f conflict_file.con ]; then
ID1=`cat conflict_ID1.con`
ID2=`cat conflict_ID2.con`
ID3=`cat conflict_ID3.con`
NAME=`cat conflict_file.con`
rm conflict_ID1.con
rm conflict_ID2.con
rm conflict_ID3.con
rm conflict_file.con
git diff $ID2 $ID1
git diff $ID2 $ID3
open -g $NAME
fi
